//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teach.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbsence
    {
        public int idStudent { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> day1 { get; set; }
        public Nullable<bool> day2 { get; set; }
        public Nullable<bool> day3 { get; set; }
        public Nullable<bool> day4 { get; set; }
        public Nullable<bool> day5 { get; set; }
        public Nullable<bool> day6 { get; set; }
        public Nullable<bool> day7 { get; set; }
        public Nullable<bool> day8 { get; set; }
        public Nullable<bool> day9 { get; set; }
        public Nullable<bool> day10 { get; set; }
        public Nullable<bool> day11 { get; set; }
        public Nullable<bool> day12 { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<double> exam { get; set; }
        public Nullable<bool> day13 { get; set; }
        public Nullable<bool> day14 { get; set; }
    
        public virtual tblStudent tblStudent { get; set; }
    }
}
