//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teach.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup
    {
        public tblGroup()
        {
            this.tblRelations = new HashSet<tblRelation>();
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public Nullable<int> idClass { get; set; }
        public int idGroup { get; set; }
        public string nameGroup { get; set; }
        public Nullable<int> maxNumber { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual ICollection<tblRelation> tblRelations { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
