//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teach.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public tblStudent()
        {
            this.tblAbsences = new HashSet<tblAbsence>();
        }
    
        public Nullable<int> idGroup { get; set; }
        public int idStudent { get; set; }
        public string nameStudent { get; set; }
        public string addressStudent { get; set; }
        public string schoolStudent { get; set; }
        public string numberParent { get; set; }
        public string notes { get; set; }
        public Nullable<int> numInLog { get; set; }
    
        public virtual ICollection<tblAbsence> tblAbsences { get; set; }
        public virtual tblGroup tblGroup { get; set; }
    }
}
