//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teach.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        public tblClass()
        {
            this.tblGroups = new HashSet<tblGroup>();
        }
    
        public int idStage { get; set; }
        public int idClass { get; set; }
        public string nameClass { get; set; }
    
        public virtual tblStage tblStage { get; set; }
        public virtual ICollection<tblGroup> tblGroups { get; set; }
    }
}
