//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teach.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelation
    {
        public int idRelation { get; set; }
        public Nullable<int> idGroup { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
    }
}
